import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

// material UI
import HomeIcon from "@mui/icons-material/Home"
import ExploreOutlinedIcon from '@mui/icons-material/ExploreOutlined';
import ShortsIcon from "@mui/icons-material/StackedLineChart"
import SubscriptionsIcon from '@mui/icons-material/SubscriptionsOutlined';
import OriginalsIcon from "@mui/icons-material/YouTube"
import YouTubeMusicIcon from '@mui/icons-material/PlayCircleOutline';

import LibraryIcon from '@mui/icons-material/VideoLibraryOutlined';
import HistoryIcon from '@mui/icons-material/History';
import YourVideosIcon from "@mui/icons-material/Slideshow"
import YourMovieIcon from '@mui/icons-material/LocalMoviesOutlined';
import WatchLaterIcon from '@mui/icons-material/AccessTime';
import DownloadsIcon from "@mui/icons-material/Download"

import FilmIcon from '@mui/icons-material/LocalMoviesOutlined';
import GamingIcon from '@mui/icons-material/SportsEsportsOutlined';
import LiveIcon from '@mui/icons-material/Sensors';
import LearnIcon from '@mui/icons-material/LightbulbOutlined';
import SportIcon from '@mui/icons-material/EmojiEventsOutlined';

import SettingsIcon from '@mui/icons-material/SettingsOutlined';
import ReportIcon from '@mui/icons-material/FlagOutlined';
import HelpIcon from '@mui/icons-material/HelpOutlineOutlined';
import FeedbackIcon from '@mui/icons-material/FeedbackOutlined';

// components

import NavIcon from '../components/Atoms/NavIcon';
import HeaderMainContainer from '../components/Organisms/HeaderMainContainer'
import Tag from '../components/Atoms/Tag';

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>(?)YouTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <HeaderMainContainer />
      </header>
      <nav className={styles.nav}>
        <div className={styles.nav__group_container_first}>
          <NavIcon Icon={<HomeIcon />} text="Home"/>
          <NavIcon Icon={<ExploreOutlinedIcon />} text="Explore" clicked/>
          <NavIcon Icon={<ShortsIcon />} text="Shorts"/>
          <NavIcon Icon={<SubscriptionsIcon />} text="Subscription"/>
          <NavIcon Icon={<OriginalsIcon />} text="Originals"/>
          <NavIcon Icon={<YouTubeMusicIcon />} text="YouTube Music"/>
        </div>
        <div className={styles.nav__group_container_second}>
          <NavIcon Icon={<LibraryIcon />} text="Library"/>
          <NavIcon Icon={<HistoryIcon />} text="History"/>
          <NavIcon Icon={<YourVideosIcon />} text="Your videos"/>
          <NavIcon Icon={<YourMovieIcon />} text="Your movies"/>
          <NavIcon Icon={<WatchLaterIcon />} text="Watch Later"/>
          <NavIcon Icon={<DownloadsIcon />} text="Downloads"/>
        </div>
        <div className={styles.nav__group_container_third}>
        <div className={styles.nav__item_text}>
          SUBSCRIPTIONS
        </div>
          
        </div>
        <div className={styles.nav__group_container_forth}>
          <div className={styles.nav__item_text}>
            MORE FROM YOUTUBE
          </div>
            <NavIcon Icon={<FilmIcon />} text="Films"/>
            <NavIcon Icon={<GamingIcon />} text="Gaming"/>
            <NavIcon Icon={<LiveIcon />} text="Live"/>
            <NavIcon Icon={<LearnIcon />} text="Learning"/>
            <NavIcon Icon={<SportIcon />} text="Sport"/>
        </div>
        <div className={styles.nav__group_container_fifth}>
          <NavIcon Icon={<SettingsIcon />} text="Settings"/>
          <NavIcon Icon={<ReportIcon />} text="Report history"/>
          <NavIcon Icon={<HelpIcon />} text="Help"/>
          <NavIcon Icon={<FeedbackIcon />} text="Send feedback"/>
        </div>
        <div className={styles.nav__group_container_sixth}>
          {`AboutPressCopyrightContact usCreatorAdvertiseDevelopers`}
        </div>
        <div className={styles.nav__group_container_seventh}>
          {`TermsPrivacyPolicy & SafetyHow YouTube worksTest new features`}
        </div>
        <div className={styles.nav__group_container_eighth}>
          {`© 2022 Google LLC
          CEO: Sundar Pichai
          Address: 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA.
          Phone: 080-822-1450 (free)`}
        </div>
      </nav>

      <aside className={styles.aside}>
        <Tag text='All' first/>
        <Tag text='JavaScript'/>
        <Tag text='React'/>
        <Tag text='Next.js'/>
        <Tag text='TypeScript'/>
        <Tag text='BlockChain' last/>
      </aside>

      <main className={styles.main}>
        main
      </main>
    </div>
  )
}

export default Home
