import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>(?)YouTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header} >
1
      </header>

      <nav className={styles.nav}>
2
      </nav>

      <aside className={styles.aside}>
3
      </aside>

      <main className={styles.main}>
        
      </main>
    </div>
  )
}

export default Home
